# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Controllo Biologico dei processi e dei prodotti dell'industria
description:      'Data analysis'
url:              http://mchiapello.github.io/Controllo-Biologico-dei-processi-e-dei-prodotti-dell-industria-2019
baseurl:          /Controllo-Biologico-dei-processi-e-dei-prodotti-dell-industria-2019
email:            chiapello.m@gmail.com
feedbackurl:      https://docs.google.com/forms/d/e/1FAIpQLSdV_polFmoukgjcs1IC0Dd4iO1rdgwFnOds28xC_ma_z4tNIw
author:
  name:           'Marco Chiapello'

github:
  repo:           https://github.com/mchiapello/Controllo-Biologico-dei-processi-e-dei-prodotti-dell-industria-2019
  #               Be sure the 'Issues' feature is activated in 'Settings'
